---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tidegphm/kevincfang.com
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R libs $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp gulpfile.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp LICENSE.md $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH